apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-ui-api
  name: vote-ui-api
spec:
  type: NodePort
  ports:
  - name: "vote-ui-api-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote-ui-api
  
